# =============================================================================
# Grafana Secrets
# =============================================================================

apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: monitoring
type: Opaque
stringData:
  admin-password: "warehouse2025"
