# PodDisruptionBudget для Frontend
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: warehouse-frontend-pdb
  namespace: warehouse
  labels:
    app: warehouse-frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: warehouse-frontend
