apiVersion: v1
kind: Service
metadata:
  name: gitlab-telegram-bot
  namespace: notifications
  labels:
    app: gitlab-telegram-bot
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30088
      name: http
  selector:
    app: gitlab-telegram-bot
