# =============================================================================
# Service для Locust Master
# =============================================================================

apiVersion: v1
kind: Service
metadata:
  name: locust-master-service
  namespace: loadtest
  labels:
    app: locust
    role: master
spec:
  type: NodePort
  ports:
    - name: web
      port: 8089
      targetPort: 8089
      nodePort: 30089
    - name: master
      port: 5557
      targetPort: 5557
    - name: master-bind
      port: 5558
      targetPort: 5558
  selector:
    app: locust
    role: master
