apiVersion: v1
kind: Service
metadata:
  name: warehouse-robot-service
  namespace: warehouse
  labels:
    app: warehouse-robot
    component: robot
spec:
  type: NodePort
  selector:
    app: warehouse-robot
  ports:
    - port: 8070
      targetPort: 8070
      nodePort: 30070
      protocol: TCP
      name: http
