apiVersion: v1
kind: Secret
metadata:
  name: warehouse-robot-secrets
  namespace: warehouse
  labels:
    app: warehouse-robot
type: Opaque
stringData:
  employee-username: "employee"
  employee-password: "password123"
